spring.datasource.url=jdbc:mysql://localhost:3306/payment_engine?useSSL=false&serverTimezone=Europe/Bucharest
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.time-zone=Europe/Bucharest


